flutter pub add auto_injector
flutter pub add build_runner
flutter pub add dev:build_runner
flutter pub add easy_localization
flutter pub add easy_localization_loader
flutter pub add equatable
flutter pub add flutter_dotenv
flutter pub add flutter_spinkit
flutter pub add font_awesome_flutter
flutter pub add format
flutter pub add hive
flutter pub add hive_flutter
flutter pub add dev:hive_generator
flutter pub add json_serializable
flutter pub add logging
flutter pub add dev:test
flutter pub add url_launcher
flutter pub add uuid
flutter pub add webview_flutter