name: Gestor Basic Steps

on: [push]

jobs:
  version:
    runs-on: ubuntu-latest
    name: version
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter --version
